#:schema https://raw.githubusercontent.com/kjanat/zed-editor/refs/heads/feature/extension-toml-schema/crates/extension_api/schemas/extension.schema.json

id             = "ldap"
name           = "LDAP"
version        = "1.0.0"
schema_version = 1
authors        = ["Kaj Kowalski <info@kajkowalski.nl>"]
description    = "Syntax highlighting for LDAP/OpenLDAP schema and LDIF files."
repository     = "https://github.com/kjanat/zed-ldap"

[grammars]
[grammars.ldap_schema]
repository = "https://github.com/kjanat/tree-sitter-ldap-schema"
rev        = "5dcd5df5d47b82664224abd7df9fd75596e4e9b6"

[grammars.ldif]
repository = "https://github.com/kjanat/tree-sitter-ldif"
rev        = "44c76a92128ab6ad55cda7f873d56760d04fa505"
