#:schema https://raw.githubusercontent.com/kjanat/zed-editor/refs/heads/feature/extension-toml-schema/crates/extension_api/schemas/extension.schema.json

id             = "ldap"
name           = "LDAP"
version        = "1.0.0"
schema_version = 1
authors        = ["Kaj Kowalski <info@kajkowalski.nl>"]
description    = "Syntax highlighting for LDAP/OpenLDAP schema and LDIF files."
repository     = "https://github.com/kjanat/zed-ldap"

[grammars]
[grammars.ldap_schema]
repository = "https://github.com/kjanat/tree-sitter-ldap-schema"
rev        = "1b43a0b6e85548937bdd8ca23b284f29a2ab0013"

[grammars.ldif]
repository = "https://github.com/kjanat/tree-sitter-ldif"
rev        = "a760e091a548d6a33e7616c0db295f4466f7a034"
